# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Build CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      VITE_SUPABASE_ENABLED: false
      VITE_SUPABASE_CLIENT_ID: ${{ secrets.SUPABASE_CLIENT_ID }}
      VITE_SUPABASE_CLIENT_KEY: ${{ secrets.VITE_SUPABASE_CLIENT_KEY }}
      VITE_SENTRY_ENABLED: true
      VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      VITE_SUPABASE_REGISTRATION_ENABLED: false
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: |
          npm ci
          unset CI && npm run build --if-present 2>1
          cd build
          tar czvf package.tar.gz *
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: build/package.tar.gz
